import { DataTypes } from "sequelize";
import sequelize from './../utils/sequelize.js';

const PhishingData = sequelize.define(
  "PhishingData",
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    url: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    length_url: DataTypes.INTEGER,
    length_hostname: DataTypes.INTEGER,
    ip: DataTypes.INTEGER,
    nb_dots: DataTypes.INTEGER,
    nb_hyphens: DataTypes.INTEGER,
    nb_at: DataTypes.INTEGER,
    nb_qm: DataTypes.INTEGER,
    nb_and: DataTypes.INTEGER,
    nb_or: DataTypes.INTEGER,
    nb_eq: DataTypes.INTEGER,
    nb_underscore: DataTypes.INTEGER,
    nb_tilde: DataTypes.INTEGER,
    nb_percent: DataTypes.INTEGER,
    nb_slash: DataTypes.INTEGER,
    nb_star: DataTypes.INTEGER,
    nb_colon: DataTypes.INTEGER,
    nb_comma: DataTypes.INTEGER,
    nb_semicolumn: DataTypes.INTEGER,
    nb_dollar: DataTypes.INTEGER,
    nb_space: DataTypes.INTEGER,
    nb_www: DataTypes.INTEGER,
    nb_com: DataTypes.INTEGER,
    nb_dslash: DataTypes.INTEGER,
    http_in_path: DataTypes.INTEGER,
    https_token: DataTypes.INTEGER,
    ratio_digits_url: DataTypes.FLOAT,
    ratio_digits_host: DataTypes.FLOAT,
    punycode: DataTypes.INTEGER,
    port: DataTypes.INTEGER,
    tld_in_path: DataTypes.INTEGER,
    tld_in_subdomain: DataTypes.INTEGER,
    abnormal_subdomain: DataTypes.INTEGER,
    nb_subdomains: DataTypes.INTEGER,
    prefix_suffix: DataTypes.INTEGER,
    shortening_service: DataTypes.INTEGER,
    path_extension: DataTypes.INTEGER,
    length_words_raw: DataTypes.INTEGER,
    char_repeat: DataTypes.INTEGER,
    shortest_words_raw: DataTypes.INTEGER,
    longest_words_raw: DataTypes.INTEGER,
    avg_words_raw: DataTypes.FLOAT,
    nb_hyperlinks: DataTypes.INTEGER,
    nb_extcss: DataTypes.INTEGER,
    login_form: DataTypes.INTEGER,
    external_favicon: DataTypes.INTEGER,
    links_in_tags: DataTypes.INTEGER,
    submit_email: DataTypes.INTEGER,
    iframe: DataTypes.INTEGER,
    onmouseover: DataTypes.INTEGER,
    empty_title: DataTypes.INTEGER,
    domain_in_title: DataTypes.INTEGER,
    status: DataTypes.INTEGER,
    check_by_user: DataTypes.INTEGER,
  },
  {
    tableName: "phishing_data",
    timestamps: false,
  }
);

export default PhishingData;
